#+title: matrix-query readme
#+author: szos

This is a package to query a matrix homeserver, to get messages and send messages, etc

* Getting Started
  1. Clone this git repo to somewhere it can be found by quicklisp, typically =~/quicklisp/local-projects/matrix-query=.
  2. Load the project with ~(ql:quickload :matrix-query)~.
     - This project depends on Drakma, and as such libssl. Your OS may have libssl under a different name than Drakma expects, and you will be hit with an error from CFFI. To get around this first find the name of your libssl with ~sudo find / -name libssl*~ and use that name in the =use-value= restart. For example on VoidLinux libssl is =libssl.so.47=, so i enter ~("libssl.so.47")~.
  3. Login by evaluating ~(login "username"  "password" :homeserver "homeserver.org/")~.
  4. You can now sync and send messages. 
    

* Contents 
** communicate.lisp
   Contains general variables and functions for talking to the matrix homeserver. Examples inlude:
   - /Variable/ *​*homeserver** 
     - *Description* a string containing the users homeserver
   - /Function/ *make-api-call*
     - *Syntax: make-api-call* /&rest api-strings/ → /string/
     - *Arguments*
       - /api-strings/ --- list of strings
     - *Description* concatenates api-strings with the homeserver to generate an api url.
** events.lisp
** matrix-query.lisp
   Contains general use functions and macros
   - /Macro/ *string-case*
     - *Syntax: string-case* /string matches &body otherwise/ → /result/
     - *Arguments*
       - /string/ --- a string to match against
       - /matches/ --- a list of possible matching strings and what to do if they match, with an implicit progn
	 - (("string" (print x) (print y))
       - /otherwise/ --- a list of forms to evaluate in the event that no strings match
     - *Description* expands into a cond statement comparing strings with /string-equal/
** misc-functions.lisp
** room-sync.lisp
** room.lisp
** session.lisp
